-- Pudle native driving companion: versioned hazard events with optional, consented position.
-- Additive: the web demo's convoys / convoy_members / obstacle_reports are unchanged.
-- Apply only to a dedicated development project until the owner approves production.

-- 1. Location-sharing consent ------------------------------------------------------------

create table public.location_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  policy_version text not null check (char_length(policy_version) between 1 and 32),
  granted_at timestamptz not null default now(),
  revoked_at timestamptz
);

alter table public.location_consents enable row level security;
revoke all on public.location_consents from anon, authenticated;
grant select on public.location_consents to authenticated;

create policy "Users can read their own location consent"
  on public.location_consents for select to authenticated
  using (user_id = (select auth.uid()));

-- 2. Hazard events (schema v1) ------------------------------------------------------------

create function public.is_valid_polyline(p jsonb, p_max integer)
returns boolean language plpgsql immutable set search_path = ''
as $$
declare
  v_point jsonb;
begin
  if jsonb_typeof(p) <> 'array' or jsonb_array_length(p) < 2 or jsonb_array_length(p) > p_max then return false; end if;
  for v_point in select * from jsonb_array_elements(p) loop
    if jsonb_typeof(v_point) <> 'array' or jsonb_array_length(v_point) <> 2
       or jsonb_typeof(v_point->0) <> 'number' or jsonb_typeof(v_point->1) <> 'number'
       or (v_point->>0)::double precision not between -90 and 90
       or (v_point->>1)::double precision not between -180 and 180 then
      return false;
    end if;
  end loop;
  return true;
end;
$$;

create table public.hazard_events (
  id uuid primary key default gen_random_uuid(),
  schema_version smallint not null default 1 check (schema_version = 1),
  convoy_id uuid not null references public.convoys(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  -- Generated by the sending phone; makes retries idempotent.
  client_event_id uuid not null,
  kind text not null check (kind in ('tree', 'debris', 'stopped_vehicle', 'animal', 'pothole', 'object', 'other')),
  -- 'convoy_member'           = tapped by a signed-in member (passenger or parked).
  -- 'driver_confirmed_camera' = the reporter's dashcam model flagged it AND the driver confirmed by voice.
  source text not null default 'convoy_member' check (source in ('convoy_member', 'driver_confirmed_camera')),
  side text not null default 'unknown' check (side in ('left', 'right', 'center', 'unknown')),
  blocks_road boolean not null default false,
  observed_at timestamptz not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  -- Optional single position at report time. Shared only with active consent.
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  accuracy_m real check (accuracy_m > 0 and accuracy_m <= 100),
  heading_deg real check (heading_deg >= 0 and heading_deg < 360),
  constraint hazard_location_complete check (
    (latitude is null) = (longitude is null) and (latitude is null) = (accuracy_m is null)
  ),
  constraint hazard_heading_needs_location check (heading_deg is null or latitude is not null),
  constraint hazard_lifetime check (expires_at > created_at and expires_at <= created_at + interval '60 minutes'),
  constraint hazard_observed_window check (
    observed_at <= created_at + interval '30 seconds' and observed_at >= created_at - interval '2 minutes'
  ),
  unique (reporter_id, client_event_id)
);

create index hazard_events_convoy_recent_idx on public.hazard_events(convoy_id, created_at desc);
create index hazard_events_expiry_idx on public.hazard_events(expires_at);
create index hazard_events_reporter_recent_idx on public.hazard_events(reporter_id, created_at desc);

alter table public.hazard_events enable row level security;
revoke all on public.hazard_events from anon, authenticated;
-- Read through RLS; writes only through report_hazard() so every rule is enforced server-side.
grant select on public.hazard_events to authenticated;

create policy "Members can read live hazard events in their active convoy"
  on public.hazard_events for select to authenticated
  using (
    expires_at > now() and exists (
      select 1 from public.convoy_members m
      join public.convoys c on c.id = m.convoy_id
      where m.convoy_id = hazard_events.convoy_id
        and m.user_id = (select auth.uid())
        and c.expires_at > now()
    )
  );

-- 3. Demo road corridors ------------------------------------------------------------------
-- A convoy member records the road once (a deliberate "record this road" drive). Receivers use it
-- to decide "same road, same direction, N meters ahead". Point order is the travel direction.
-- This is the only stored path; individual drivers' movements are never uploaded.

create table public.road_corridors (
  id uuid primary key default gen_random_uuid(),
  convoy_id uuid not null references public.convoys(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 60),
  points jsonb not null check (public.is_valid_polyline(points, 2000)),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days')
);

create index road_corridors_convoy_idx on public.road_corridors(convoy_id, created_at desc);
alter table public.road_corridors enable row level security;
revoke all on public.road_corridors from anon, authenticated;
grant select on public.road_corridors to authenticated;

create policy "Members can read corridors of their active convoy"
  on public.road_corridors for select to authenticated
  using (
    expires_at > now() and exists (
      select 1 from public.convoy_members m
      join public.convoys c on c.id = m.convoy_id
      where m.convoy_id = road_corridors.convoy_id
        and m.user_id = (select auth.uid())
        and c.expires_at > now()
    )
  );

-- 4. Functions ----------------------------------------------------------------------------

create function public.report_hazard(
  p_convoy_id uuid,
  p_kind text,
  p_client_event_id uuid,
  p_observed_at timestamptz default null,
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_accuracy_m real default null,
  p_heading_deg real default null,
  p_source text default 'convoy_member',
  p_side text default 'unknown',
  p_blocks_road boolean default false
)
returns public.hazard_events
language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_row public.hazard_events;
  v_observed timestamptz := coalesce(p_observed_at, now());
begin
  if v_user is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_client_event_id is null then
    raise exception 'client_event_id is required' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.convoy_members m
    join public.convoys c on c.id = m.convoy_id
    where m.convoy_id = p_convoy_id and m.user_id = v_user and c.expires_at > now()
  ) then
    raise exception 'Not a member of an active convoy' using errcode = '42501';
  end if;

  -- Idempotent retry: same sender + client ID returns the original row unchanged.
  select * into v_row from public.hazard_events
    where reporter_id = v_user and client_event_id = p_client_event_id;
  if found then
    return v_row;
  end if;

  if exists (
    select 1 from public.hazard_events r
    where r.reporter_id = v_user and r.created_at > now() - interval '5 seconds'
  ) then
    raise exception 'Wait a moment before sending another report' using errcode = '54000';
  end if;

  if p_source = 'driver_confirmed_camera' and p_latitude is null then
    raise exception 'Camera reports need a location' using errcode = '22023';
  end if;

  if v_observed < now() - interval '2 minutes' or v_observed > now() + interval '10 seconds' then
    raise exception 'Observation time is stale or in the future' using errcode = '22023';
  end if;

  if p_latitude is not null or p_longitude is not null or p_accuracy_m is not null or p_heading_deg is not null then
    if not exists (
      select 1 from public.location_consents lc
      where lc.user_id = v_user and lc.revoked_at is null
    ) then
      raise exception 'Location sharing consent required' using errcode = '42501';
    end if;
  end if;

  insert into public.hazard_events(
    convoy_id, reporter_id, client_event_id, kind, source, side, blocks_road,
    observed_at, created_at, expires_at, latitude, longitude, accuracy_m, heading_deg)
  values (
    p_convoy_id, v_user, p_client_event_id, p_kind, coalesce(p_source, 'convoy_member'),
    coalesce(p_side, 'unknown'), coalesce(p_blocks_road, false),
    least(v_observed, now()), now(),
    -- A blocked road stays relevant longer than loose debris.
    now() + case when coalesce(p_blocks_road, false) then interval '30 minutes' else interval '15 minutes' end,
    p_latitude, p_longitude, p_accuracy_m, p_heading_deg)
  returning * into v_row;
  return v_row;
end;
$$;

create function public.save_corridor(p_convoy_id uuid, p_name text, p_points jsonb)
returns uuid
language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_id uuid;
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if not exists (
    select 1 from public.convoy_members m join public.convoys c on c.id = m.convoy_id
    where m.convoy_id = p_convoy_id and m.user_id = v_user and c.expires_at > now()
  ) then
    raise exception 'Not a member of an active convoy' using errcode = '42501';
  end if;
  if not exists (select 1 from public.location_consents lc where lc.user_id = v_user and lc.revoked_at is null) then
    raise exception 'Location sharing consent required' using errcode = '42501';
  end if;
  insert into public.road_corridors(convoy_id, created_by, name, points)
    values (p_convoy_id, v_user, trim(p_name), p_points)
    returning id into v_id;
  return v_id;
end;
$$;

create function public.set_location_consent(p_granted boolean, p_policy_version text)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if p_granted then
    insert into public.location_consents(user_id, policy_version, granted_at, revoked_at)
      values (v_user, p_policy_version, now(), null)
      on conflict (user_id) do update
        set policy_version = excluded.policy_version, granted_at = now(), revoked_at = null;
  else
    update public.location_consents set revoked_at = now()
      where user_id = v_user and revoked_at is null;
    -- Withdrawing consent also removes positions from this user's still-stored reports.
    update public.hazard_events
      set latitude = null, longitude = null, accuracy_m = null, heading_deg = null
      where reporter_id = v_user and latitude is not null;
    -- Corridors expire immediately (invisible through RLS); retention cleanup removes them.
    update public.road_corridors
      set expires_at = now(), points = '[[0,0],[0,0]]'::jsonb
      where created_by = v_user and expires_at > now();
  end if;
end;
$$;

-- Lets a member leave; reading access ends immediately because policies check membership live.
revoke all on function public.report_hazard(uuid, text, uuid, timestamptz, double precision, double precision, real, real, text, text, boolean) from public, anon;
revoke all on function public.set_location_consent(boolean, text) from public, anon;
revoke all on function public.save_corridor(uuid, text, jsonb) from public, anon;
grant execute on function public.report_hazard(uuid, text, uuid, timestamptz, double precision, double precision, real, real, text, text, boolean) to authenticated;
grant execute on function public.set_location_consent(boolean, text) to authenticated;
grant execute on function public.save_corridor(uuid, text, jsonb) to authenticated;

alter publication supabase_realtime add table public.hazard_events;

-- Supabase grants EXECUTE to PUBLIC by default; restrict to signed-in users.
revoke execute on function public.report_hazard(uuid, text, uuid, timestamptz, double precision, double precision, real, real, text, text, boolean) from public;
revoke execute on function public.save_corridor(uuid, text, jsonb) from public;
revoke execute on function public.set_location_consent(boolean, text) from public;
revoke execute on function public.limit_obstacle_reports() from public, anon, authenticated;
